name: Build & Deploy WordPress
on:
  push:
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tar 
        run: |
          TIMESTAMP=$(date -u +%Y%m%d_%H%M%S)
          ARCHIVE=app_${TIMESTAMP}.tar.gz
          tar -czf $ARCHIVE .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact to S3
        run: |
          aws s3 cp $ARCHIVE s3://omnia-app/$ARCHIVE
