name: Build & Deploy WordPress
on:
  push:
    branches: 
      - master

      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tar 
        run: |
          TIMESTAMP=$(date -u +%Y%m%d_%H%M%S)
          ARCHIVE=app_${TIMESTAMP}.tar.gz
          git archive --format=tar.gz -o $ARCHIVE HEAD
          echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact to S3
        run: |
          aws s3 cp $ARCHIVE s3://omnia-app/$ARCHIVE

      - name: Download archive and extract it
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=omnia-app" \
            --comment "test command" \
            --parameters 'commands=[
                "aws s3 cp s3://omnia-app/'${ARCHIVE}' /tmp/'${ARCHIVE}'"
                , "mkdir -p /tmp/app_extract",
                "tar -xvf /tmp/'${ARCHIVE}' -C /tmp/app_extract",
                "rsync -av  /tmp/app_extract/ /var/www/html/",
                "chown -R apache:apache /var/www/html",
                "ln -sfn /wp-content/uploads /var/www/html/wp-content/uploads"]' \
            --region us-east-1



